export const allergenPaths: {[key: number]: any} = {
  1: require('../assets/icons/gluten.png'),
  2: require('../assets/icons/crustaceans.png'),
  3: require('../assets/icons/eggs.png'),
  4: require('../assets/icons/fish.png'),
  5: require('../assets/icons/peanuts.png'),
  6: require('../assets/icons/soy.png'),
  7: require('../assets/icons/dairies.png'),
  8: require('../assets/icons/nuts.png'),
  9: require('../assets/icons/celery.png'),
  10: require('../assets/icons/mustard.png'),
  11: require('../assets/icons/sesame.png'),
  12: require('../assets/icons/sulfites.png'),
  13: require('../assets/icons/lupins.png'),
  14: require('../assets/icons/molluscs.png'),
};
